- name: create swapfile
  shell: |
    test -e /swapfile || ( \
      fallocate -l {{ ubuntu_common_setup_swap_size }} /swapfile && \
      chmod 600 /swapfile && \
      mkswap /swapfile && \
      swapon /swapfile \
    )
  when: ubuntu_common_setup_swapfile | bool

- name: add swapfile to fstab
  mount:
    src: /swapfile
    path: none
    fstype: swap
    state: present
    opts: sw
  when: ubuntu_common_setup_swapfile | bool

- name: configure swappiness
  sysctl:
    name: vm.swappiness
    value: '10'
    sysctl_set: yes
    state: present
    reload: yes
